# Use the AWS Lambda Python image as the base
FROM public.ecr.aws/lambda/python:3.11.2024.03.04.10

# Set the working directory inside the container
WORKDIR /app

# Copy all files and folders into the container
COPY . /app

# Ensure executables have the correct permissions
RUN chmod +x /app/OpenUtau
RUN chmod -R 777 app/

# Install any Python dependencies required by your application
RUN pip install --no-cache-dir -r requirements.txt

# Set PYTHONPATH to include /app directory
ENV PYTHONPATH="/app"

# Verify files are copied correctly
RUN ls -R /app

# Specify Lambda handler
CMD ["openutau_script.lambda_handler"]
